version: "3"
services:
  homer:
    extends:
      file: /home/voxelin/homer/docker-compose.yml
      service: homer
    networks:
      connector:
        ipv4_address: 172.20.128.1
  portrainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks:
      connector:
        ipv4_address: 172.20.128.2
  proxy:
    extends:
      file: /home/voxelin/proxy-router/docker-compose.yml
      service: app
    networks:
      connector:
        ipv4_address: 172.20.128.3

networks:
  connector:
    external: true
volumes:
  portainer_data:
